spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sjt-project?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin888
    driver-class-name: com.mysql.jdbc.Driver
    table-prefix: sjt_

  http:
    encoding:
      charset: UTF-8

  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/static/

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.iisquare.sjt.api.mvc.NamingStrategy

  thymeleaf:
    mode: HTML
    suffix: .htm
    cache: false

custom:
  date:
    format: yyyy-MM-dd HH:mm:ss
  uploads:
    path: docs/uploads
    uri: http://127.0.0.1:8080/files
