server:
  port: 8002
  servlet:
    session:
      timeout: 2592000
      cookie:
        max-age: 2592000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sjt-project?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin888
    driver-class-name: com.mysql.jdbc.Driver
    table-prefix: sjt_
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800

  http:
    encoding:
      charset: UTF-8

  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/static/

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.iisquare.sjt.api.mvc.NamingStrategy

  thymeleaf:
    mode: HTML
    suffix: .htm
    cache: false

custom:
  date:
    format: yyyy-MM-dd HH:mm:ss
  uploads:
    path: docs/uploads
    uri: http://127.0.0.1:8080/files
